### ISSUE TITLE
Deamon Prince Close Combat Weapons.

### ISSUE THREAD

**Issue by XLPuDDing** [BSData/wh40kbs2#10]
When i chose a Weapon when playing khorne Daemon kin.  it tells me i have one to many weapons selected and the error will only go away if i uncheck close combat weapon.  I checked the codex and choosing an artifact of Slaughter for a weapon does not replace the close combat weapon. I am using battlescribe 2.00.01 and using the ZZ data file for BS2

**Comment by cartag** [comment]
Under the Wargear list: 

"A model may instead replace one weapon with one of the following:
Artefact list" 

Working as intended.
