### ISSUE TITLE
Rename the Repo?

### ISSUE THREAD

**Issue by Jonskichov** [BSData/wh40kbs2#6]
Several people have been trying to download this repo in 1.15.07 and running into issues...

Any chance we could rename this repo to have a "Z" in front (or something) so it's sorted to the bottom of the list?

**Comment by cartag** [comment]
I will when I get to a computer unless somebody can before then

**Comment by amis92** [comment]
honestly, it's not reasonable. it breaks things almost always. it's easier to just change description, which is what actually shows on AppSpot. I'll go ahead and to that.

**Comment by Kohato** [comment]
Go ahead and rename now - I think I'm the only one working on files in here at the moment and it won't mess with my work.

**Comment by cartag** [comment]
Repo shouldn't need renamed, the description should be enough. Anybody who is using it now either had it from before or is intentionally obtuse
